export const monokaiProTheme = {
  name: 'Monokai Pro',
  type: 'dark' as const,
  colors: {
    'editor.background': '#2d2a2e',
    'editor.foreground': '#fcfcfa',
    'editor.lineHighlightBackground': '#363337',
    'editor.selectionBackground': '#5b595c',
    'editor.inactiveSelectionBackground': '#403e41',
    'editor.findMatchBackground': '#5b595c',
    'editor.findMatchHighlightBackground': '#403e4180',
    'editorCursor.foreground': '#fcfcfa',
    'editorLineNumber.foreground': '#5b595c',
    'editorLineNumber.activeForeground': '#c1c0c0',
    'editorIndentGuide.background': '#403e41',
    'editorIndentGuide.activeBackground': '#5b595c',
    'editorBracketMatch.background': '#5b595c50',
    'editorBracketMatch.border': '#5b595c',
    'editorGutter.addedBackground': '#a9dc76',
    'editorGutter.modifiedBackground': '#78dce8',
    'editorGutter.deletedBackground': '#ff6188',

    'sideBar.background': '#221f22',
    'sideBar.foreground': '#c1c0c0',
    'activityBar.background': '#221f22',
    'activityBar.foreground': '#fcfcfa',
    'activityBar.inactiveForeground': '#5b595c',
    'activityBarBadge.background': '#ffd866',
    'activityBarBadge.foreground': '#2d2a2e',

    'titleBar.activeBackground': '#2d2a2e',
    'titleBar.activeForeground': '#fcfcfa',
    'titleBar.inactiveBackground': '#221f22',

    'tab.activeBackground': '#2d2a2e',
    'tab.activeForeground': '#fcfcfa',
    'tab.inactiveBackground': '#221f22',
    'tab.inactiveForeground': '#939293',
    'tab.border': '#221f22',
    'tab.activeBorderTop': '#ffd866',
    'editorGroupHeader.tabsBackground': '#221f22',

    'statusBar.background': '#221f22',
    'statusBar.foreground': '#727072',
    'statusBar.debuggingBackground': '#ff6188',
    'statusBar.debuggingForeground': '#fcfcfa',

    'input.background': '#403e41',
    'input.foreground': '#fcfcfa',
    'input.border': '#5b595c',
    'input.placeholderForeground': '#727072',

    'list.activeSelectionBackground': '#403e41',
    'list.activeSelectionForeground': '#ffd866',
    'list.inactiveSelectionBackground': '#363337',
    'list.hoverBackground': '#363337',
    'list.highlightForeground': '#ffd866',

    'panel.background': '#221f22',
    'panel.border': '#403e41',
    'panelTitle.activeBorder': '#ffd866',
    'panelTitle.activeForeground': '#ffd866',

    'terminal.background': '#221f22',
    'terminal.foreground': '#fcfcfa',
    'terminal.ansiBlack': '#403e41',
    'terminal.ansiRed': '#ff6188',
    'terminal.ansiGreen': '#a9dc76',
    'terminal.ansiYellow': '#ffd866',
    'terminal.ansiBlue': '#fc9867',
    'terminal.ansiMagenta': '#ab9df2',
    'terminal.ansiCyan': '#78dce8',
    'terminal.ansiWhite': '#fcfcfa',
    'terminal.ansiBrightBlack': '#727072',
    'terminal.ansiBrightRed': '#ff6188',
    'terminal.ansiBrightGreen': '#a9dc76',
    'terminal.ansiBrightYellow': '#ffd866',
    'terminal.ansiBrightBlue': '#fc9867',
    'terminal.ansiBrightMagenta': '#ab9df2',
    'terminal.ansiBrightCyan': '#78dce8',
    'terminal.ansiBrightWhite': '#fcfcfa',

    'button.background': '#ffd866',
    'button.foreground': '#2d2a2e',
    'button.hoverBackground': '#fce566',

    'badge.background': '#ffd866',
    'badge.foreground': '#2d2a2e',

    'focusBorder': '#727072',
    'foreground': '#fcfcfa',
    'widget.shadow': '#19181a',
    'errorForeground': '#ff6188',
    'icon.foreground': '#c1c0c0',

    'gitDecoration.addedResourceForeground': '#a9dc76',
    'gitDecoration.modifiedResourceForeground': '#ffd866',
    'gitDecoration.deletedResourceForeground': '#ff6188',
    'gitDecoration.untrackedResourceForeground': '#a9dc76',
    'gitDecoration.ignoredResourceForeground': '#5b595c',

    'scrollbarSlider.background': '#5b595c50',
    'scrollbarSlider.hoverBackground': '#5b595c80',
    'scrollbarSlider.activeBackground': '#5b595cb0',

    'notifications.background': '#403e41',
    'notifications.foreground': '#fcfcfa',

    'diffEditor.insertedTextBackground': '#a9dc7633',
    'diffEditor.removedTextBackground': '#ff618833',

    'breadcrumb.foreground': '#939293',
    'breadcrumb.focusForeground': '#fcfcfa',
    'breadcrumb.activeSelectionForeground': '#ffd866',

    'minimap.findMatchHighlight': '#ffd86666',
    'minimap.selectionHighlight': '#5b595c99',
  },
  tokenColors: [
    { scope: ['comment'], settings: { foreground: '#727072', fontStyle: 'italic' } },
    { scope: ['string'], settings: { foreground: '#FFD866' } },
    { scope: ['constant.numeric'], settings: { foreground: '#AB9DF2' } },
    { scope: ['constant.language'], settings: { foreground: '#AB9DF2' } },
    { scope: ['keyword', 'storage.type', 'storage.modifier'], settings: { foreground: '#FF6188' } },
    { scope: ['keyword.control'], settings: { foreground: '#FF6188' } },
    { scope: ['keyword.operator'], settings: { foreground: '#FF6188' } },
    { scope: ['entity.name.type', 'entity.name.class'], settings: { foreground: '#A9DC76', fontStyle: 'italic' } },
    { scope: ['entity.name.function'], settings: { foreground: '#A9DC76' } },
    { scope: ['entity.name.tag'], settings: { foreground: '#FF6188' } },
    { scope: ['entity.other.attribute-name'], settings: { foreground: '#78DCE8', fontStyle: 'italic' } },
    { scope: ['variable', 'variable.other'], settings: { foreground: '#FCFCFA' } },
    { scope: ['variable.parameter'], settings: { foreground: '#FC9867', fontStyle: 'italic' } },
    { scope: ['support.function'], settings: { foreground: '#78DCE8' } },
    { scope: ['support.type', 'support.class'], settings: { foreground: '#78DCE8', fontStyle: 'italic' } },
    { scope: ['punctuation.definition.tag'], settings: { foreground: '#FF6188' } },
    { scope: ['meta.type.annotation'], settings: { foreground: '#78DCE8' } },
  ],
};
