export const solarizedDarkTheme = {
  name: 'Solarized Dark',
  type: 'dark' as const,
  colors: {
    'editor.background': '#002b36',
    'editor.foreground': '#839496',
    'editor.lineHighlightBackground': '#073642',
    'editor.selectionBackground': '#274642',
    'editor.inactiveSelectionBackground': '#073642',
    'editor.findMatchBackground': '#586e7580',
    'editor.findMatchHighlightBackground': '#586e7540',
    'editorCursor.foreground': '#d30102',
    'editorLineNumber.foreground': '#586e75',
    'editorLineNumber.activeForeground': '#839496',
    'editorIndentGuide.background': '#073642',
    'editorIndentGuide.activeBackground': '#586e75',
    'editorBracketMatch.background': '#073642',
    'editorBracketMatch.border': '#586e75',
    'editorGutter.addedBackground': '#859900',
    'editorGutter.modifiedBackground': '#268bd2',
    'editorGutter.deletedBackground': '#dc322f',

    'sideBar.background': '#00212b',
    'sideBar.foreground': '#839496',
    'activityBar.background': '#00212b',
    'activityBar.foreground': '#839496',
    'activityBar.inactiveForeground': '#586e75',
    'activityBarBadge.background': '#268bd2',
    'activityBarBadge.foreground': '#fdf6e3',

    'titleBar.activeBackground': '#002b36',
    'titleBar.activeForeground': '#839496',

    'tab.activeBackground': '#002b36',
    'tab.activeForeground': '#fdf6e3',
    'tab.inactiveBackground': '#00212b',
    'tab.inactiveForeground': '#586e75',
    'tab.border': '#002b36',
    'tab.activeBorderTop': '#268bd2',
    'editorGroupHeader.tabsBackground': '#00212b',

    'statusBar.background': '#00212b',
    'statusBar.foreground': '#586e75',

    'input.background': '#003847',
    'input.foreground': '#839496',
    'input.border': '#586e75',

    'list.activeSelectionBackground': '#073642',
    'list.activeSelectionForeground': '#fdf6e3',
    'list.inactiveSelectionBackground': '#073642',
    'list.hoverBackground': '#073642',
    'list.highlightForeground': '#268bd2',

    'panel.background': '#002b36',
    'panel.border': '#073642',

    'terminal.background': '#002b36',
    'terminal.foreground': '#839496',
    'terminal.ansiBlack': '#073642',
    'terminal.ansiRed': '#dc322f',
    'terminal.ansiGreen': '#859900',
    'terminal.ansiYellow': '#b58900',
    'terminal.ansiBlue': '#268bd2',
    'terminal.ansiMagenta': '#d33682',
    'terminal.ansiCyan': '#2aa198',
    'terminal.ansiWhite': '#eee8d5',
    'terminal.ansiBrightBlack': '#002b36',
    'terminal.ansiBrightRed': '#cb4b16',
    'terminal.ansiBrightGreen': '#586e75',
    'terminal.ansiBrightYellow': '#657b83',
    'terminal.ansiBrightBlue': '#839496',
    'terminal.ansiBrightMagenta': '#6c71c4',
    'terminal.ansiBrightCyan': '#93a1a1',
    'terminal.ansiBrightWhite': '#fdf6e3',

    'button.background': '#268bd2',
    'button.foreground': '#fdf6e3',

    'focusBorder': '#268bd2',
    'foreground': '#839496',
    'errorForeground': '#dc322f',

    'gitDecoration.addedResourceForeground': '#859900',
    'gitDecoration.modifiedResourceForeground': '#b58900',
    'gitDecoration.deletedResourceForeground': '#dc322f',
    'gitDecoration.untrackedResourceForeground': '#859900',
    'gitDecoration.ignoredResourceForeground': '#586e75',

    'diffEditor.insertedTextBackground': '#85990033',
    'diffEditor.removedTextBackground': '#dc322f33',

    'breadcrumb.foreground': '#586e75',
    'breadcrumb.focusForeground': '#839496',
    'breadcrumb.activeSelectionForeground': '#fdf6e3',
  },
  tokenColors: [
    { scope: ['comment'], settings: { foreground: '#586e75', fontStyle: 'italic' } },
    { scope: ['string'], settings: { foreground: '#2AA198' } },
    { scope: ['constant.numeric'], settings: { foreground: '#D33682' } },
    { scope: ['constant.language'], settings: { foreground: '#B58900' } },
    { scope: ['keyword', 'storage.type', 'storage.modifier'], settings: { foreground: '#859900' } },
    { scope: ['keyword.control'], settings: { foreground: '#859900' } },
    { scope: ['entity.name.type', 'entity.name.class'], settings: { foreground: '#B58900' } },
    { scope: ['entity.name.function'], settings: { foreground: '#268BD2' } },
    { scope: ['entity.name.tag'], settings: { foreground: '#268BD2' } },
    { scope: ['entity.other.attribute-name'], settings: { foreground: '#93A1A1' } },
    { scope: ['variable', 'variable.other'], settings: { foreground: '#839496' } },
    { scope: ['support.function'], settings: { foreground: '#268BD2' } },
    { scope: ['support.type', 'support.class'], settings: { foreground: '#B58900' } },
    { scope: ['punctuation'], settings: { foreground: '#839496' } },
  ],
};
